esphome:
  name: esphome-web-f1ba90
  friendly_name: Bryggers Bluetooth Proxy
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 320ms
    window: 30ms

bluetooth_proxy:
  active: true